-- Seed 30 micronutrient questions (DE) across 4 thematic stages (6/9/12/3)
--
-- Stage 1: Blinde Flecken          — population-level deficits & myths
-- Stage 2: Küchen-Code             — preparation & bioavailability
-- Stage 3: Pille trifft Teller     — drugs, drinks & daily habits that rob nutrients
-- Stage 4: Die Kehrseite           — nutrient partnerships & rivalries (finisher, 3 Qs)
--
-- Re-running this seed: TRUNCATE wipes questions and cascades to user_progress.

truncate table questions restart identity cascade;

-- Stage 1: Blinde Flecken (6)
insert into questions (stage, order_in_stage, prompt, options, correct_idx, explanation) values
(1, 1,
 'Vitamin D wird in der Haut durch Sonnenlicht gebildet und ist wichtig für Knochen, Muskeln und Immunsystem. Wie viele Deutsche haben im Winter einen Mangel?',
 '["Etwa 25 %", "Etwa jeder Zweite (52 %)", "Etwa 75 %"]',
 1,
 'Von Oktober bis März steht die Sonne in Deutschland so tief, dass die UV-B-Strahlung physikalisch zu schwach ist, um in der Haut Vitamin D zu bilden — egal wie lange man rausgeht. Im Sommer sind nur 8,3 % der Deutschen unterversorgt, im Winter explodiert dieser Wert auf 52 %. Die Folgen: mehr Muskelschwäche, häufigere Infekte, stärkere Winterblues-Symptome, langfristig Osteoporoserisiko. Die einzigen verlässlichen Quellen von Oktober bis März sind Supplemente oder fetter Seefisch (Lachs, Makrele).'),
(1, 2,
 'Folsäure schützt ungeborene Kinder vor schweren Rückenmarks- und Hirnfehlbildungen. Wie viele deutsche Frauen im gebärfähigen Alter erreichen die empfohlene Zufuhr ohne Supplemente?',
 '["Etwa die Hälfte", "Etwa ein Viertel", "Nur etwa 5 %"]',
 2,
 'Folsäure (ein B-Vitamin) ist entscheidend für die Zellteilung — bei Schwangeren für die Bildung des Neuralrohrs, aus dem Gehirn und Rückenmark entstehen. In Deutschland erreichen nur 4,8 % der Frauen (15–45 Jahre) die empfohlene Zufuhr ohne Supplemente. Die USA hat seit 1998 Pflichtanreicherung von Mehl — die Rate der Neuralrohrdefekte sank dort um ca. 30 %. Deutschland hat diese Maßnahme nicht. Deshalb: Jede Frau im gebärfähigen Alter (nicht erst mit Kinderwunsch) sollte ein Folsäure-Supplement erwägen — denn die kritische Zeit liegt vor der ersten Periode nach Empfängnis.'),
(1, 3,
 'Wie viel Prozent des Salzes in deutschen Fertigprodukten ist jodiert?',
 '["Etwa die Hälfte", "Etwa 28 %", "Nur etwa 9 %"]',
 2,
 'Jod ist der zentrale Baustein der Schilddrüsenhormone — bei Mangel drohen Schilddrüsenvergrößerung, Entwicklungsstörungen bei Kindern und Müdigkeit bei Erwachsenen. Obwohl die Jodprophylaxe in Deutschland lange als Erfolg galt, sinken die Werte wieder. Vom gesamten verzehrten Salz ist nur 28 % jodiert, beim Salz in Fertigprodukten (das 70–80 % unserer Gesamt-Salzaufnahme ausmacht!) sind es nur 9 %. Die mediane Jodzufuhr liegt bei nur 75 µg/Tag — 40 % des Empfohlenen. Trend-Salze wie Himalaya-, Meersalz und Fleur de Sel verschärfen das Problem — sie sind nicht jodiert. Die WHO stuft Deutschland wieder als jodinsuffizient ein.'),
(1, 4,
 'Eine 78-Jährige wird zunehmend vergesslich und unsicher beim Gehen — frühe Demenz? Welcher einfache Bluttest sollte zuerst gemacht werden?',
 '["TSH (Schilddrüse)", "Vitamin B12", "Vitamin D"]',
 1,
 'Vitamin B12 ist essenziell für Nervenhüllen und Blutbildung — bei Mangel: Gedächtnisprobleme, Gangunsicherheit, Demenz-ähnliche Symptome, oft ohne die klassische Anämie. Im Alter kommt ein „perfekter Sturm" zusammen: atrophische Gastritis (bei 20–30 % der Senioren) hemmt B12-Freisetzung aus Nahrung, Magensäureblocker blockieren die Aufnahme weiter, und Metformin verstärkt das Problem. Ergebnis: 27 % der deutschen Senioren haben niedrige B12-Spiegel (KORA-Age-Studie). Viele dieser Fälle werden als „Alterserscheinung" oder beginnende Demenz fehlinterpretiert — obwohl sie mit einer Spritze reversibel wären.'),
(1, 5,
 'Selen ist ein Spurenelement, das die Schilddrüse schützt und vor bestimmten Krebserkrankungen. Wie viel Selen enthält deutsches Brot im Vergleich zu amerikanischem?',
 '["Etwa gleich viel", "Etwa ein Drittel", "Bis zu 20× weniger"]',
 2,
 'Selen aktiviert die Enzyme, die Schilddrüsenhormone umwandeln und schützt Zellen vor oxidativem Schaden. Europäische Böden sind geologisch selenarm — daher enthält europäisches Getreide nur 0,028 µg/g Selen, nordamerikanisches 0,518 µg/g. Die tägliche Selenzufuhr in Europa liegt bei nur 28–31 µg — weit unter den empfohlenen 55–70 µg. Finnland hat das Problem erkannt und düngt seit 1984 mit Selenat. Deutschland macht das nicht. Praktische Konsequenz: Bei Schilddrüsenproblemen oder Autoimmunerkrankungen lohnt ein Blick auf die Selenversorgung.'),
(1, 6,
 'Stimmt die berühmte Geschichte, dass Spinat wegen eines verrutschten Kommas als eisenreich gilt?',
 '["Ja, ein Chemiker setzte das Komma falsch", "Nein — die Kommafehler-Geschichte ist selbst ein Mythos", "Teils — der Fehler wurde 1937 korrigiert"]',
 1,
 'Eisen ist für den Sauerstofftransport im Blut unverzichtbar — bei Mangel kommt Müdigkeit, blasse Haut, Konzentrationsschwäche. Der Kommafehler-Mythos selbst wurde nie bewiesen. Aber das zugrundeliegende Eisenproblem beim Spinat ist real: Spinat enthält zwar 2,7 mg Eisen/100 g (ähnlich wie ein Steak!), aber der Körper absorbiert daraus nur 1,7 % — aus Fleisch dagegen ~20 %. Effektiv landen aus 100 g Spinat 0,04 mg im Blut, aus 100 g Steak 0,50 mg — ein 10-facher Praxis-Unterschied. Popeye hat also doppelt falsch gelegen.');

-- Stage 2: Küchen-Code (9)
insert into questions (stage, order_in_stage, prompt, options, correct_idx, explanation) values
(2, 1,
 'Was passiert, wenn Sie Salat mit fettfreiem Dressing essen?',
 '["Sie nehmen alle Vitamine normal auf — Hauptsache Salat", "Sie nehmen etwa die Hälfte der schützenden Pflanzenstoffe auf", "Die für Augen, Haut und Immunsystem wichtigsten Stoffe landen fast gar nicht in Ihrem Körper"]',
 2,
 'Tomaten, Karotten und grünes Blattgemüse enthalten fettlösliche Pflanzenstoffe, die die Augen vor Makuladegeneration schützen, die Haut vor UV-Schäden bewahren und das Immunsystem stärken — Beta-Carotin, Lycopin, Lutein. Ohne Fett im Dressing können diese Stoffe die Darmwand nicht passieren und werden wieder ausgeschieden. Schon 1 EL Olivenöl reicht, um sie voll aufzunehmen. Das fettfreie Dressing aus dem Bioladen ist ernährungsphysiologisch also eine verpasste Chance.'),
(2, 2,
 'Tomaten enthalten einen roten Pflanzenstoff, der nachweislich das Risiko für Prostatakrebs senkt und das Herz schützt. In welcher Form nimmt der Körper am meisten davon auf?',
 '["Rohe Tomate im Salat", "Tomatensauce, mit Olivenöl gekocht", "Tomatensaft, kalt"]',
 1,
 'Der schützende Pflanzenstoff Lycopin ist in rohen Tomaten eingesperrt — hinter robusten Zellwänden, die der Körper kaum aufbrechen kann. Kochen öffnet die Zellen, und Öl transportiert das Lycopin ins Blut. Gekochte Tomatensauce mit Olivenöl steigert den Lycopinspiegel im Blut um 82 % gegenüber rohen Tomaten. Rohe Tomate im Salat ohne Fett? Nahezu kein messbarer Effekt. Das italienische Sugo ist ernährungsphysiologisch dem rohen Tomatensalat weit überlegen — eine der wenigen Gelegenheiten, bei denen „verarbeitet" gesünder ist als „frisch".'),
(2, 3,
 'Möhren enthalten einen Pflanzenstoff, aus dem der Körper Vitamin A bildet — wichtig für Sehkraft und Immunsystem. Wie viel davon nimmt der Körper aus rohen Möhren auf?',
 '["Etwa gleich viel wie aus gekochten", "Etwa die Hälfte", "Nur etwa ein Siebtel — rohe Möhren sind kaum nutzbar"]',
 2,
 'Beta-Carotin ist die Vorstufe von Vitamin A — wichtig für Nachtsicht, Hautregeneration und Immunabwehr. In rohen Möhren ist es hinter stabilen Zellwänden eingesperrt: Der Körper nimmt nur 11 % auf. Kochen bricht die Zellwände auf — aus gekochten Möhren kommen 75 % an. Schon 1 TL Olivenöl reicht, um die Aufnahme noch weiter zu steigern. Der Möhrensticks-Snack beim Meeting? Vitaminmäßig fast eine Nullnummer. Besser: kurz dünsten und mit etwas Öl servieren.'),
(2, 4,
 'Spinat enthält fast so viel Calcium wie Milch. Wie viel davon kommt tatsächlich in Ihren Knochen an?',
 '["Etwa so viel wie aus Milch (27 %)", "Etwa die Hälfte (15 %)", "Nur etwa 5 % — der Rest wird ungenutzt ausgeschieden"]',
 2,
 'Calcium ist unverzichtbar für starke Knochen und Zähne — aber nur, wenn der Körper es auch aufnehmen kann. Spinat enthält Oxalsäure, die Calcium im Darm so fest bindet, dass es unverdaut wieder ausgeschieden wird. Von den 99 mg Calcium in 100 g Spinat nimmt der Körper nur 5 % auf. Um so viel Calcium wie aus einem Glas Milch zu bekommen, müssten Sie 1,6 kg Spinat essen. Besser: Grünkohl, Brokkoli, Pak Choi — bei ihnen sind es bis zu 40 %. Der „grüne Smoothie mit Spinat" für starke Knochen ist also eher Wunschdenken.'),
(2, 5,
 'Kurkuma enthält einen entzündungshemmenden Wirkstoff, der gegen Gelenkschmerzen und zur Herzgesundheit eingesetzt wird. Wie viel davon kommt ohne schwarzen Pfeffer im Blut an?',
 '["Etwa die Hälfte", "Etwa ein Fünftel", "Praktisch nichts — der Körper baut ihn in Minuten ab"]',
 2,
 'Der goldgelbe Wirkstoff in Kurkuma (Curcumin) wird vom Körper so schnell zerlegt, dass er kaum messbar ins Blut gelangt. Eine Prise schwarzer Pfeffer enthält einen Stoff, der diesen Abbau blockiert — und erhöht die Aufnahme um das 20-Fache (2.000 %). Die indische Küche kombiniert beides seit Jahrhunderten intuitiv. Der „Goldene Milch"-Trend ohne Pfeffer? Meistens ein teures Placebo. Bei Kurkuma-Kapseln: Etikett prüfen — ohne Piperin (Pfefferextrakt) praktisch wirkungslos.'),
(2, 6,
 'Sauerteigbrot und Hefebrot sehen ähnlich aus — aber welches liefert mehr Eisen, Zink und Magnesium ins Blut?',
 '["Etwa gleich", "Hefebrot, weil schneller aufgegangen", "Sauerteigbrot — deutlich mehr"]',
 2,
 'Getreide enthält einen natürlichen Schutzstoff (Phytinsäure), der sich um Mineralien wie Eisen, Zink, Magnesium und Kupfer legt und sie im Darm unaufnehmbar macht. Sauerteig-Fermentation baut 62–90 % dieses Blockierers ab — Hefe nur 38 %. Das heißt: Aus demselben Weizen kommen bei Sauerteig deutlich mehr Mineralien im Körper an. Besonders relevant für Vegetarier, Veganer und Menschen mit marginalem Eisen- oder Zinkstatus. Das deutsche Sauerteigbrot ist ernährungsphysiologisch also nicht nur Tradition, sondern klar überlegen. Schnelles Hefebrot und Toastbrot sind dagegen Mineralstoff-Blockierer.'),
(2, 7,
 'Brokkoli aus dem Supermarktregal liegt 2 Wochen im Kühlschrank. Tiefkühlbrokkoli liegt 2 Wochen im Gefrierfach. Wo ist jetzt mehr Vitamin C drin?',
 '["Im „frischen\" Brokkoli", "In beiden etwa gleich viel", "Im Tiefkühlbrokkoli"]',
 2,
 'Vitamin C ist wichtig für Immunabwehr, Kollagenbildung und Eisenaufnahme — aber es zerfällt rasant durch Licht, Sauerstoff und Zeit. „Frischer" Supermarktbrokkoli hat oft Tage bis Wochen Transport und Lagerung hinter sich. Tiefkühlgemüse wird innerhalb von Stunden nach der Ernte blanchiert und eingefroren — auf dem Höhepunkt des Nährstoffgehalts. Nach 14 Tagen Kühlschranklagerung sinkt der Vitamin-C-Gehalt unter das Tiefkühlniveau. Tiefkühlgemüse ist also keine „zweite Wahl" — oft die bessere Wahl.'),
(2, 8,
 'Welche Zubereitungsart erhält am meisten Vitamin C in Gemüse?',
 '["Kochen im Wasser", "Dampfgaren", "Mikrowelle (gleichauf mit Dampfgaren)"]',
 2,
 'Vitamin C ist hitze- und vor allem wasserempfindlich — beim Kochen wird es zum Großteil aus dem Gemüse ins Kochwasser gespült, das dann weggeschüttet wird. In einer Studie verlor Mangold beim Kochen 100 % des Vitamin C. Mikrowelle und Dampfgaren schonen hingegen beides — kurze Garzeit, kein Wasser: über 90 % Erhalt. Entgegen dem Vorurteil „Mikrowellen zerstören Nährstoffe" ist das Gegenteil der Fall. Rangfolge für maximale Nährstoffe: Dampf ≥ Mikrowelle > Braten > Kochen.'),
(2, 9,
 'Ein Patient kauft die günstigste Magnesium-Packung (Oxid) und nimmt 400 mg täglich — ohne Besserung der Krämpfe. Warum?',
 '["Die Dosis ist zu niedrig", "Der Körper nimmt nur etwa 4 % auf — der Rest wird ausgeschieden", "Magnesium wirkt nicht gegen Krämpfe"]',
 1,
 'Auf der Packung steht zwar „400 mg Magnesium" — aber das heißt nicht, dass 400 mg im Körper ankommen. Magnesiumoxid, die günstigste und meistverkaufte Form, hat nur ~4 % Bioverfügbarkeit. Von 400 mg werden also effektiv nur ~16 mg verwertet. Magnesiumcitrat, -glycinat oder -malat sind um ein Vielfaches besser aufnehmbar (25–30 %). Bei Magnesium zählt also nicht, was auf der Packung steht, sondern was beim Zellstoffwechsel ankommt. Die teurere Form ist pro Milligramm verwertetes Magnesium oft die günstigere.');

-- Stage 3: Pille trifft Teller (12)
insert into questions (stage, order_in_stage, prompt, options, correct_idx, explanation) values
(3, 1,
 'Eine Patientin mit Eisenmangel trinkt regelmäßig Schwarztee zum Essen. Um wieviel reduziert das die Eisenaufnahme?',
 '["Um etwa 30 %", "Um etwa 50 %", "Um bis zu 94 % — fast komplette Blockade"]',
 2,
 'Eisen ist unverzichtbar für Sauerstofftransport und Energie — Mangel macht müde, blass und konzentrationsschwach. Die Bitterstoffe im Schwarztee (Tannine) binden Eisen im Darm zu unlöslichen Klumpen — die Aufnahme kollabiert um bis zu 94 %. Die gute Nachricht: Wartet man nur 1 Stunde nach der Mahlzeit mit dem Tee, halbiert sich der hemmende Effekt. Für eisenmangelgefährdete Patienten gilt also nicht „kein Tee" — sondern „Tee mit 1 Stunde Abstand". Gleiches gilt für Grüntee und Kaffee. Milch im Tee macht es übrigens noch schlimmer.'),
(3, 2,
 'Frau M. trinkt ihren Kaffee 1 Stunde VOR dem Frühstück. Ist das ein Problem für ihre Eisenaufnahme?',
 '["Ja, Kaffee blockiert Eisen generell", "Nein — nur Kaffee MIT oder NACH dem Essen blockiert Eisen", "Kaffee hat keinen Einfluss auf Eisen"]',
 1,
 'Die Bitterstoffe im Kaffee (Chlorogensäuren) binden Eisen aus der Nahrung — aber nur, wenn Kaffee gleichzeitig mit oder nach der Mahlzeit konsumiert wird. Dann sinkt die Eisenaufnahme um bis zu 83 %. Wird Kaffee vor dem Essen getrunken, ist die Bindung zur Mahlzeit vorbei und der Effekt null. Wichtig: Nicht das Koffein ist der Täter — Decaf hemmt genauso stark. Pragmatische Regel: Erst Kaffee, dann Frühstück — oder nach dem Essen mindestens 1 Stunde Pause.'),
(3, 3,
 'Ein Patient mit Schilddrüsenunterfunktion nimmt morgens Levothyroxin und trinkt direkt danach Kaffee. Wie stark leidet die Aufnahme?',
 '["Um etwa 5–10 %", "Um etwa 30 %", "Um etwa 60 %"]',
 1,
 'Levothyroxin ersetzt das fehlende Schilddrüsenhormon und muss sehr exakt dosiert werden — schon kleine Schwankungen bringen Stoffwechsel, Energie und Gewicht aus dem Gleichgewicht. Kaffee innerhalb von 60 Minuten nach der Tablette reduziert die Aufnahme um 29–36 %. Calcium- und Eisenpräparate erfordern sogar 4 Stunden Abstand. Die Realität: 50 % der Patienten finden diese Timing-Regel belastend, 13 % vergessen die Tablette deshalb komplett. Alternative bei Non-Compliance: Flüssiges Levothyroxin — dieses zeigt keine Kaffee-Interaktion, selbst 5 Minuten vorher.'),
(3, 4,
 'Ein Patient nimmt seine Cholesterin-Tablette abends, trinkt aber morgens ein Glas Grapefruitsaft — 12 Stunden Abstand. Reicht das?',
 '["Ja, 12 Stunden reichen", "Nein, der Effekt hält bis zu 24 Stunden", "Nein, der Effekt hält bis zu 72 Stunden — der Saft hebelt das Medikament tagelang aus"]',
 2,
 'Grapefruitsaft zerstört ein wichtiges Entgiftungsenzym in der Darmwand, das viele Medikamente auf die richtige Dosis herunterbremst. Ohne dieses Enzym gelangt bis zu 13,5-mal mehr Wirkstoff ins Blut — bei Simvastatin ein ernstes Muskel- und Nierenrisiko. Das Enzym muss komplett neu gebildet werden, was 3 bis 7 Tage dauert. „Zeitlich versetzt einnehmen" funktioniert hier nicht — bei Grapefruit gibt es nur ganz oder gar nicht. Betrifft auch einige Blutdrucksenker, Immunsuppressiva und Schmerzmittel.'),
(3, 5,
 'Wie stark kann ein Eisen- oder Calcium-Präparat die Aufnahme des Antibiotikums Ciprofloxacin reduzieren?',
 '["Um etwa 15 %", "Um etwa 40 %", "Um bis zu 64 %"]',
 2,
 'Antibiotika aus der Gyrasehemmer- und Tetracyclin-Gruppe (Cipro, Levo, Doxycyclin) bilden mit Calcium, Magnesium, Eisen, Zink und Aluminium (in Antazida) unlösliche Klumpen im Darm — und sind dann wirkungslos. Aluminium-Antazida senken Ciprofloxacin um 85 %. Und trotzdem: 74,5 % aller Klinikpatienten bekommen beides gleichzeitig — eine häufige, vermeidbare Ursache für Therapieversagen. Regel für Beratung: Diese Antibiotika 2 Stunden vor oder 6 Stunden nach Mineralien und Antazida einnehmen. Auch Milch und eisenreiches Essen zählen dazu.'),
(3, 6,
 'Ein 68-jähriger Diabetiker nimmt seit 6 Jahren Metformin und klagt über Kribbeln und Taubheit in den Füßen. Was sollte vor der Diagnose „diabetische Nervenschädigung" unbedingt getestet werden?',
 '["Schilddrüsenwerte", "Vitamin B12", "Folsäure"]',
 1,
 'Vitamin B12 ist für die Isolierung der Nerven unentbehrlich — bei Mangel werden Hände und Füße kribbelig, taub, später entstehen Gangunsicherheit und sogar Demenz-ähnliche Symptome. Metformin senkt die B12-Aufnahme um 3–5 % pro Einnahmejahr; nach 5 Jahren haben 19 % der Patienten einen Mangel. Die Tücke: Die Nervensymptome sehen klinisch identisch aus wie eine diabetische Neuropathie — aber der B12-Mangel ist komplett reversibel, die diabetische Schädigung nicht. Ein 15-Euro-Bluttest kann Patienten vor jahrzehntelanger Fehldiagnose bewahren.'),
(3, 7,
 'Die Antibabypille senkt gezielt den Spiegel mehrerer B-Vitamine. Welcher Mangel wäre bei einer ungeplanten Schwangerschaft am gefährlichsten?',
 '["Magnesiummangel", "Folsäuremangel — weil er Neuralrohrdefekte beim Baby verursacht", "Vitamin-D-Mangel"]',
 1,
 'Folsäure ist entscheidend für die Bildung des Gehirns und Rückenmarks beim ungeborenen Kind — in den ersten 4 Schwangerschaftswochen, bevor die Frau überhaupt weiß, dass sie schwanger ist. Die Pille senkt Folsäure, B6, B12, Magnesium, Zink und Selen. Die gefährliche Ironie: Das Medikament, das Schwangerschaft verhindert, verarmt genau die Reserven, die in den frühesten Wochen einer ungeplanten Schwangerschaft kritisch wären. Die WHO stuft diese Wechselwirkung als „klinisch hochrelevant" ein. Beratung: 400 µg Folsäure ab Pillen-Tag 1, nicht erst bei Kinderwunsch.'),
(3, 8,
 'Eine Patientin nimmt seit 5 Jahren Omeprazol gegen Sodbrennen und hat trotz 400 mg Magnesium täglich Muskelkrämpfe. Warum?',
 '["Die Magnesiumdosis ist zu niedrig", "Der Magensäureblocker verhindert die Aufnahme so stark, dass selbst Supplemente versagen", "Es liegt gar kein Magnesiummangel vor"]',
 1,
 'Magnesium entspannt Muskeln, regelt Herzrhythmus und aktiviert über 300 Enzyme — bei Mangel kommen Krämpfe, Herzstolpern, Müdigkeit, Kopfschmerzen. Die FDA warnt seit 2011: Magensäureblocker (PPIs) wie Omeprazol können die Magnesium-Aufnahme so stark lahmlegen, dass orale Supplemente den Mangel nicht mehr korrigieren können. Bei 61 % der Langzeit-PPI-Anwender (≥ 5 Jahre) liegt ein Magnesiummangel vor. Der einzige Ausweg: PPI absetzen oder niedriger dosieren. Gleichzeitig können PPIs Vitamin B12 und Calcium-Aufnahme reduzieren — mit Fraktur- und Nervenfolgen.'),
(3, 9,
 'Warum empfiehlt die Deutsche Gesellschaft für Ernährung Rauchern deutlich mehr Vitamin C als Nichtrauchern?',
 '["Weil Raucher schlechter essen", "Weil Rauchen den Vitamin-C-Umsatz nahezu verdoppelt — der Körper verbraucht es massiv gegen den oxidativen Stress", "Es ist kein Unterschied nötig"]',
 1,
 'Vitamin C ist das wichtigste wasserlösliche Antioxidans im Körper — es fängt schädliche freie Radikale ab, bevor sie Zellen zerstören. Zigarettenrauch produziert solche Radikale in enormen Mengen. Die DGE empfiehlt deshalb: rauchende Männer 155 mg/Tag statt 110 mg — ein Plus von 41 %. Selbst Passivrauchen verdoppelt die Mangel-Prävalenz. Ein konkreter Beratungsansatz: Ein Glas Orangensaft oder eine Paprika am Tag extra — kostet nichts und repariert einen Teil des Schadens.'),
(3, 10,
 'Chronisch gestresste Menschen haben auffällig oft Magnesium-Mangel. Wie hängt das zusammen?',
 '["Zufall — beides ist unabhängig", "Teufelskreis: Stress verbraucht Magnesium → Mangel macht stressanfälliger → mehr Stress → weniger Magnesium", "Der Körper gleicht das über die Nahrung aus"]',
 1,
 'Magnesium dämpft die Stressachse — es beruhigt den Sympathikus, senkt Cortisol, entspannt Muskeln und verbessert Schlaf. Unter Stress schüttet der Körper aber Magnesium aus den Zellen und scheidet mehr über den Urin aus. Der resultierende Mangel macht dann stressempfindlicher — das HPA-System reagiert stärker auf die nächsten Belastungen. Bei bis zu 45 % chronisch gestresster Menschen findet sich ein subklinischer Mangel. Zusätzlich stört Mg-Mangel den Schlaf (blockiert Melatoninbildung) — der zweite Teufelskreis. In einer Studie senkte 350 mg Magnesiumcitrat/Tag über 24 Wochen das Cortisol messbar. Ein Supplement kann die Spirale durchbrechen.'),
(3, 11,
 'Vitamin E galt lange als schützendes Antioxidans fürs Herz. Was zeigte eine Meta-Analyse mit 135.000 Teilnehmern zu hohen Dosen (≥ 400 IE/Tag)?',
 '["Senkt Herzerkrankungen", "Kein Effekt", "Erhöht die Gesamtsterblichkeit"]',
 2,
 'Antioxidantien neutralisieren freie Radikale — aber freie Radikale sind nicht nur schlecht. Sie sind auch wichtige Signalmoleküle für Immunabwehr und Zellgesundheit. Hochdosiertes Vitamin E (≥ 400 IE/Tag) stört dieses Gleichgewicht: Die Miller-Meta-Analyse zeigte erhöhte Sterblichkeit, hochgerechnet +39 Tote pro 10.000 Personen. Risiko beginnt bereits bei > 150 IE/Tag. Vitamin E aus Nüssen, Samen, Pflanzenölen? Wunderbar. Hochdosierte Pillen? Besser nicht. „Mehr ist besser" ist bei Antioxidantien ein teurer Irrtum.'),
(3, 12,
 'Eine Schwangere nimmt täglich ein Multivitamin mit Vitamin A. Ab welcher Dosis steigt das Fehlbildungsrisiko signifikant?',
 '["Ab 5.000 IE", "Ab 10.000 IE", "Ab 25.000 IE"]',
 1,
 'Vitamin A ist wichtig für Zellwachstum und Entwicklung — aber genau das macht es in der frühen Schwangerschaft gefährlich. Eine Studie mit 22.748 Schwangerschaften zeigte: Frauen mit > 10.000 IE Retinol (Vitamin A) täglich hatten ein 4,8× erhöhtes Risiko für schwere Fehlbildungen — 1 von 57 Babys war betroffen. Besonders kritisch: Eine Portion Rinderleber enthält 27.000 IE — das Dreifache der Gefahrengrenze. Das Risiko betrifft nur tierisches Vitamin A (Retinol), nicht das Beta-Carotin aus Gemüse. Beratung: In der Schwangerschaft keine Leber, Multivitamine auf Retinolgehalt prüfen.');

-- Stage 4: Die Kehrseite (3) — finisher
insert into questions (stage, order_in_stage, prompt, options, correct_idx, explanation) values
(4, 1,
 'Ein Patient nimmt hochdosiertes Vitamin D — aber die Spiegel steigen nicht. Was fehlt?',
 '["Vitamin K", "Magnesium — es ist der „Schlüssel\", der Vitamin D aktiviert", "Zink"]',
 1,
 'Vitamin D aus der Pille oder der Sonne ist inaktiv — der Körper muss es in zwei Schritten (in Leber und Niere) in die wirksame Form umwandeln. Alle beteiligten Enzyme brauchen Magnesium als Cofaktor. Fehlt Magnesium, bleibt das Vitamin D im Blut nutzlos liegen. In einer Studie zeigte Magnesium-Gabe einen doppelten Effekt: es hob niedrige Vitamin-D-Spiegel an und senkte zu hohe. Die Konsequenz: Wer hochdosiert Vitamin D nimmt, aber Magnesium-Mangel hat, verschwendet möglicherweise sein Geld. Vitamin D immer zusammen mit Magnesium supplementieren.'),
(4, 2,
 'Vitamin D erhöht die Calcium-Aufnahme aus der Nahrung. Aber was sorgt dafür, dass das Calcium in den Knochen landet — statt in den Arterien?',
 '["Vitamin C", "Vitamin K2", "Vitamin E"]',
 1,
 'Vitamin D öffnet die Calcium-Schleusen im Darm — es erhöht die Calciumaufnahme von 15 % auf bis zu 40 %. Aber Calcium ist ein zweischneidiges Schwert: Im Knochen macht es stark, in den Arterien verursacht es Verkalkungen und Herzinfarkte. Vitamin K2 aktiviert zwei Schlüsselproteine: eines, das Calcium in den Knochen einbaut, und eines, das Calcium aus den Arterien fernhält. Ohne K2 bleiben beide inaktiv. Metapher: „D öffnet die Schleuse, K2 dirigiert den Verkehr." Wer hochdosiert Vitamin D nimmt, sollte K2 (MK-7) dazu nehmen — Faustregel: 100 µg K2 pro 1.000 IE D3.'),
(4, 3,
 'Eine 76-Jährige nimmt seit 11 Monaten 50 mg Zink täglich (für „Immunabwehr"). Sie entwickelt Gangstörungen und fällt bei Blutwerten auf. Die Ursache?',
 '["Altersbedingte Nervenschwäche", "Zink hat ihren Kupfer-Spiegel so gesenkt, dass Nervensystem und Blutbildung leiden", "Vitamin-B12-Mangel"]',
 1,
 'Kupfer ist essenziell für Blutbildung, Nervenhüllen und Immunzellen. Zink und Kupfer konkurrieren im Darm um dasselbe Aufnahmesystem — und Zink gewinnt immer. Bei > 40 mg Zink täglich wird die Kupferaufnahme so stark gedrosselt, dass nach Wochen bis Monaten ein klinisch manifester Kupfermangel entsteht: Blutarmut, Immunschwäche, Myelopathie und Ataxie — teils irreversibel. Seit COVID nehmen viele Patienten dauerhaft hochdosiert Zink. Die offizielle Obergrenze liegt bei 40 mg/Tag. Über 40 mg: Kupfer-Monitoring zwingend.');
